services:

  redis:
    container_name: cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/cache
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

    volumes:
      - ./mongo-volume:/app/db/data/mdb  
    ports: 
      - 27017:27017  

  torrent: 
    container_name: torrent-client
    build: 
      context: .
      dockerfile: torrent.dockerfile
    environment: 
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81  
    depends_on:
      - redis    
    volumes:
      - asset-volume:/app/download
  

  scrapper:
    container_name: torrent-scrapper
    build: 
      context: .
      dockerfile: dockerfile
    volumes:
      - asset-volume:/app/download
      - db:/app/db/data
    environment:
      - QUIALITY=1080p  
      - TORRENT_LIMIT=3
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=torrent
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81  
    depends_on:
      - mongo  
      - torrent
    

  
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plexms
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - ADVERTISE_IP=192.168.0.1:32400/
      - HOSTNAME=PlexServer
      - TZ="Europe/London"
    volumes:
      -  asset-volume:/data/tvshows
      - ./plex/config:/config
    restart: always
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp


volumes:
  asset-volume: 
  db:
  cache:
    driver: local


